tools:
    external_code_coverage: true
checks:
    php:
        excluded_dependencies:
            - magento/framework
            - magento/module-authorization
            - magento/module-backend
            - magento/module-backup
            - magento/module-catalog
            - magento/module-catalog-import-export
            - magento/module-catalog-inventory
            - magento/module-catalog-rule
            - magento/module-catalog-url-rewrite
            - magento/module-checkout
            - magento/module-cms
            - magento/module-cms-url-rewrite
            - magento/module-config
            - magento/module-contact
            - magento/module-cron
            - magento/module-customer
            - magento/module-developer
            - magento/module-directory
            - magento/module-downloadable
            - magento/module-eav
            - magento/module-email
            - magento/module-gift-message
            - magento/module-grouped-product
            - magento/module-import-export
            - magento/module-indexer
            - magento/module-integration
            - magento/module-media-storage
            - magento/module-msrp
            - magento/module-newsletter
            - magento/module-page-cache
            - magento/module-payment
            - magento/module-product-alert
            - magento/module-quote
            - magento/module-reports
            - magento/module-require-js
            - magento/module-review
            - magento/module-rss
            - magento/module-rule
            - magento/module-sales
            - magento/module-sales-rule
            - magento/module-sales-sequence
            - magento/module-security
            - magento/module-shipping
            - magento/module-store
            - magento/module-tax
            - magento/module-theme
            - magento/module-translation
            - magento/module-ui
            - magento/module-url-rewrite
            - magento/module-user
            - magento/module-variable
            - magento/module-widget
            - magento/module-wishlist
